model:
  num_agents: 128
  num_traffic_lights: 32
  agent_features: 10
  light_features: 5
  latent_queries: 192
  hidden_dim: 512
  num_layers: 8
  num_heads: 8
  num_diffusion_steps: 32

training:
  batch_size: 32  # Reduced for testing
  learning_rate: 3.0e-4
  max_steps: 1200000
  checkpoint_interval: 10000
  eval_interval: 5000
  gradient_clip: 1.0

simulation:
  timesteps: 91
  history_steps: 11
  future_steps: 80
  replan_interval: 40

data:
  data_path: "path/to/womd"  # Update this
  train_split: "train"
  val_split: "val"
  test_split: "test"